version: "3.1"

services:
  db:
    container_name: shareable-mongo-db
    image: mongo:latest
    restart: always
    volumes:
      - ./svc-vol:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ShareableDB
    ports:
      - 27017:27017
